### ISSUE TITLE
Update MAC database

### ISSUE THREAD

**Issue by fat-tire** [tux-mind/platform_external_nmap#1]
Quick request-- nmap is a little old, but the MAC database could be updated just by updating [this file here](https://github.com/nmap/nmap/blob/master/nmap-mac-prefixes).  See cSploit issue [#484](https://github.com/cSploit/android/issues/484)

Thanks!

**Comment by tux-mind** [comment]
fixed in f927a87e26fbbc57604739cd2a7ea43714469a90

thanks :blush:
